# ==========================================
# 1. DICTIONARY DỮ LIỆU ĐỊNH NGHĨA PROMPT
# ==========================================

STYLE_PROMPT_MAP = {
     "2D": "a flat 2D vector art illustration. Clean, distinct bold black outlines, minimalist paper-cut aesthetic. Background composed of large, solid-color fills. No realistic shading, no texture grain, no three-dimensional volume. Bold geometric silhouettes, highly saturated distinct colors.",
    "3D": "a high-resolution 3D computer graphics render, volumetric lighting. Soft-claymorphism and high-gloss plastic material texture. Detailed ray tracing, soft diffused shadows, textured surface imperfections, tactile physical finish with visible polygon structure and high-gloss reflections.",
    "Realism": "a 4K hyperrealistic photograph. True DSLR skin grain, hyper-detailed textures, intricate pores, individual hair strands. Shot with shallow depth of field (aperture f/1.8), natural diffused lighting, photorealistic lifelike detail, extremely sharp focus on the main subject.",
    "Animeart": "a vibrant 2D anime-style character illustration. Classic cell shading, Makoto Shinkai-vibe lighting gradients, expressive vibrant eyes with sharp highlights. Precise black lineart, Ghibli-esque atmospheric glow, soft vibrant color transitions, Japanese manga aesthetic.",
    "Cinematic": "a widescreen cinematic movie scene, anamorphic lens flare. Dramatic chiaroscuro lighting, visible film grain. Epic composition, color-graded to a specific dark or warm palette, suspenseful movie-poster mood, heavy vignetting, IMAX quality.",
    "Digitalart": "a detailed digital painting. Soft, layered textured brushwork simulating oil paints on a digital canvas. Visible brush strokes, rich layered texture, soft gradients, fantasy concept art style, DeviantArt or ArtStation trending quality.",
    "Pixelart": "an 8-bit retro pixel art sprite sheet. Limited 16-color palette, dithering technique. Isometric or flat sprite constructed from distinct blocky edges and dot matrix patterns. Gameboy aesthetic, retro arcade vibe, visible pixel grid.",
    "Vangoghart": "an oil painting in the style of Vincent van Gogh. Thick expressive impasto brush strokes, visible heavy canvas texture. Swirling skies, vivid emotional post-impressionist colors (cobalt blue, emerald green, intense yellow), dynamic painted movement.",
    "Cyberpunk": "a detailed cyberpunk city night scene. High contrast synthetic neon lights (magenta, cyan), towering skyscrapers, flying cars, mechanical cyborg limbs. Rainy pavement with wet neon reflections, high-tech low-life sci-fi aesthetic.",
    "Lofi": "a grainy, nostalgic lofi hip hop style illustration. Soft lighting, visible VHS glitches, scan lines, noise texture. Purple haze filter, cozy bedroom environment, relaxed nostalgic mood, retro anime aesthetic.",
    "Vintage": "a faded sepia-tone vintage photograph. Heavy film grain, noise, scratches, polaroid frame. Muted desaturated colors, chemical degradation marks, tea-stained edges, 1980s retro fashion elements, analog film feel.",
    "Horror": "a dark, unsettling gothic horror painting. Eerie fog, dark nightmare landscape, heavy vignetting, unsettling shadows. Eldritch terror, macabre details, gore-red accents, scary and creepy cinematic lighting.",
    "Minimalism": "a simple, clean minimalist art piece. Single central subject, excessive negative space, monochromatic smooth background. Simple diffused gradient, no texture or distractions, geometric harmony, zen-like essential shapes.",
    "Cute": "an adorable chibi-style kawaii illustration. Small plump creature, massive sparkly eyes, soft pastel colors. Squishy shapes, tiny limbs, ethereal glow, Sanrio aesthetic, wholesome joy, fluffy cozy environment.",
    "Cool": "a high-fashion editorial photo, urban magazine cover. Confident edgy streetwear posing, hypebeast style. Textured urban surfaces, gritty street setting, bold text overlays, vogue aesthetic, highly stylish.",
    "Aesthetic": "a dreamy poetic artistic composition. Soft focus, ethereal atmosphere, soft-lighting gradient (warm pinks, baby blues). Beautiful bokeh, vaporwave elements, curated mood, tumblr style visual.",
    "Fantasy": "a detailed fantasy oil painting. Mythical creatures, glowing auras, medieval armor, magic spells. Ancient runestones, enchanted forests, heavy textured paintwork, epic quest atmosphere, mystical illumination.",
    "Comic": "a bold retro superhero comic book panel. Dramatic action lines, halftone dots, bold black ink outlines. Onomatopoeia text, speech bubbles, pop art vibrant ink wash, Marvel/DC style dynamic shading.",
    "Scifi": "a futuristic science fiction scene. High-tech interstellar laboratory, holographic user interfaces, mecha design plating. Cold sterile lighting, laser beams, starlight backgrounds, zero gravity environment."
}

COLOR_PROMPT_MAP = {
   "Black": "overwhelmingly dominated by deep obsidian and midnight void black tones. Matte black materials, jet black silk textures, heavy charcoal shadows, ink-washed darkness, completely devoid of bright colors.",
    "White": "pristine environment flooded with bright white surfaces. Snow-capped purity, ivory elegance, pearl sheen, alabaster textures. Soft white light bouncing everywhere, overexposed clinical or heavenly atmosphere.",
    "Blackandwhite": "strict monochrome grayscale image, completely devoid of color hues. High contrast noir lighting, dramatic chiaroscuro, sharp transitions between pure black shadows and stark white highlights, charcoal sketch aesthetic.",
    "Red": "dominated by strong vivid red hues. Crimson objects, ruby radiance, scarlet velvet textures. Burning ember saturation, cherry blossom red, blood orange intensity, commanding fiery visual weight.",
    "Yellow": "saturated with bright cheerful yellow tones. Golden yellow objects, canary brilliance, honey gold lighting. Lemon zest textures, amber glow, saffron silk, warm vibrant energetic atmosphere.",
    "Blue": "immersed in deep vibrant blue hues. Cyan tones, sapphire depth, cobalt skies, electric blue sparks. Azure mist, navy professional tones, cool calming light interaction.",
    "Green": "defined by lush vibrant green tones. Emerald foliage, mossy earth, jade stones, lime vibrancy. Deep forests, sage leaves, organic natural photosynthesis atmosphere.",
    "Pink": "saturated with soft and vibrant pinks. Magenta highlights, hot pink objects, rose petals, blush satin textures. Coral tints, bubblegum pop, dusty mauve, playful romantic aesthetic.",
    "Orange": "dominated by warm glowing orange hues. Sunset colors, pumpkin orange, apricot warmth, terracotta clay. Copper metallic sheens, marmalade glow, autumnal energetic fiery ambiance.",
    "Pastel": "soft desaturated color palette. Pale pinks, baby blues, mint creams, soft yellows. Lavender haze, peach fuzz, macaron palette, misty sky blue. Gentle, airy, highly aesthetic.",
    "Hologram": "visually complex holographic texture. Iridescent rainbow reflections, metallic silver surfaces shifting colors, opalescent shimmers, liquid mercury rainbows. Glitch aesthetic, soap bubble film.",
    "Vintage": "retro color grading dominated by sepia tones and warm brown filters. Faded polaroids, grainy film stock, daguerreotype finishes. Muted, desaturated, tea-stained nostalgic feel.",
    "Colorful": "explosion of rainbow colors and multiple highly vibrant hues. Kaleidoscope burst, psychedelic swirl, Mardi Gras palette. Stained glass reflections, technicolor dream aesthetic, highly saturated.",
    "Neutral": "calm earthy palette dominated by beige, cream, skin tones. Oatmeal linen, taupe elegance, mushroom greys, sandstone, light khaki. Organic, muted, grounding minimalist shades.",
    "Light": "high-key lighting setup creating a very bright luminous image. Overexposed ethereal feel, backlit glows, morning haze, soft focus brightness. Wash out heavy shadows, studio ring light effect.",
    "Dark": "low-key lighting setup dominated by heavy shadows. Moody vignette, night scene, obscured silhouettes, heavy noir atmosphere, dim candlelit cinematic shadows.",
    "Warm": "bathed in warm lighting and orange/yellow undertones. Golden hour sunlight, cozy atmospheres, candlelight flickers, campfire radiance. Sepia sunsets, brassy reflections, heated nostalgic temperature.",
    "Cold": "visually chilling image dominated by blue and cyan undertones. Winter atmospheres, icy surfaces, frosty glazes, steel blue chills. Moonlight silver, fluorescent clinical lighting, freezing isolated mood.",
    "Neon": "vibrant glowing aesthetic driven by artificial neon signs. Cyberpunk lights, laser beams, vaporwave magenta, toxic lime glows, night city pulses. Ultraviolet streaks, high-contrast synthetic lighting.",
    "Gradient": "focused on smooth seamless color transitions. Blurred backgrounds, ombre transitions, dusk-to-dawn bleeds. Silk-smooth blending, watercolor washes, no harsh lines.",
    "Purple": "saturated with deep purples and violets. Lavender objects, royal amethyst, plum velvet, orchid blooms. Dark violet mysteries, lilac breezes, regal magical atmospheric aesthetic.",
    "Brown": "rustic composition dominated by earthy brown tones. Wooden textures, chocolate colors, rich soil, mahogany wood. Espresso crema, rustic leather, cinnamon spice, weathered bronze.",
    "Grey": "sleek muted palette of greys and silvers. Concrete walls, silver metals, ash colors, slate stones. Gunmetal industrial elements, misty fogs, pewter shines, brutalist somber aesthetic."
}

SUBJECT_PROMPT_MAP = {
    "sport": "dynamic sports action, high-speed athletic movement, realistic sweat droplets on skin, intense competition, stadium lighting, motion blur on limbs, energetic atmosphere, competitive spirit",
    "football": "professional soccer match, vibrant green football pitch with white chalk lines, players in realistic woven uniforms, stadium crowd with bokeh effect, kicking a highly detailed soccer ball, action sports photography",
    "messi": "Lionel Messi, Argentina football legend, unmistakable facial features, short beard, wearing number 10 jersey, dynamic athletic dribbling posture, realistic skin texture with sweat, highly detailed sports portrait",
    "lamineyamal": "Lamine Yamal, young football prodigy, FC Barcelona jersey, accurate facial likeness, agile movement, rising star, dynamic sports portrait, youthful athletic physique",
    "ronaldo": "Cristiano Ronaldo, CR7, Portuguese football icon, unmistakable facial structure, iconic Siuuu celebration pose, extremely muscular athletic physique, intense determination, highly detailed sports photography",
    "mbappe": "Kylian Mbappe, French football star, accurate facial likeness, explosive sprinting speed, running with the soccer ball, realistic sports action, dynamic motion blur",
    "flamengo": "Clube de Regatas do Flamengo, highly detailed red and black horizontally striped jersey, team crest, Maracana stadium background, passionate Brazilian football fans, red flares",
    "sepalmeiras": "SE Palmeiras, highly detailed green and white jersey, Palmeiras crest, Brazilian football club, Allianz Parque stadium, passionate supporters, energetic sports scene",
    "sccorinthianspaulista": "SC Corinthians Paulista, crisp black and white kit, Corinthians emblem, Brazilian football, Neo Quimica Arena, faithful crowd, intense stadium lighting",
    "juventus": "Juventus FC, classic black and white vertical striped jersey, Italian Serie A football, J logo, Allianz Stadium, professional sports portrait, dramatic stadium lighting",
    "realmadrid": "Real Madrid CF, iconic pristine white kit, Real Madrid crest, Santiago Bernabeu stadium background, Los Blancos, royal football club, champions league elite atmosphere",
    "dortmund": "Borussia Dortmund, vibrant yellow and black jersey, BVB logo, Signal Iduna Park, massive 'Yellow Wall' fan choreography in background, passionate German football scene",
    "chelsea": "Chelsea FC, royal blue jersey, Chelsea lion crest, Stamford Bridge stadium, Premier League action, intense professional football atmosphere, vivid blue tones",
    "intermiami": "Inter Miami CF, distinctive pastel pink and black jersey, heron crest, MLS soccer action, South Florida tropical vibe, bright sunny stadium lighting",
    "neymar": "Neymar Jr, Brazilian football star, accurate facial features, flashy dribbling skills, joyful athletic expression, dynamic sports action, detailed tattoos, highly realistic portrait",
    "manchesterunited": "Manchester United, iconic red jersey, Red Devils crest, Old Trafford stadium background, premier league, intense historical football club atmosphere",
    "manchestercity": "Manchester City, sky blue jersey, Man City crest, Etihad stadium, modern tactical football play, dynamic passing motion, premier league champions",
    "bayernmunich": "FC Bayern Munich, red and white kit, Bayern crest, Allianz Arena, powerful German football powerhouse, intense athletic focus, Mia San Mia culture",
    "barcelona": "FC Barcelona, classic blaugrana red and blue striped jersey, FCB crest, Camp Nou stadium, tiki-taka passing style, passionate Spanish football scene",
    "liverpool": "Liverpool FC, iconic solid red jersey, Liverbird crest, Anfield stadium, intense premier league match, highly emotional sports photography",
    "sonheungmin": "Son Heung-min, South Korean football star, accurate facial likeness, Tottenham Hotspur kit, iconic camera photo celebration pose, dynamic forward, realistic portrait",
    "atleticomadrid": "Atletico de Madrid, red and white vertically striped jersey, Atleti crest, Metropolitano stadium, intense gritty defensive football, Spanish La Liga",
    "arsenal": "Arsenal FC, distinctive red jersey with white sleeves, cannon crest, Emirates stadium, the Gunners, premier league action, clean sports photography",
    "cricket": "professional cricket match, batsman in protective gear swinging a wooden cricket bat, hitting a red leather ball, 22-yard pitch, stadium crowd, test match whites or vibrant T20 colors",
    "dhoni": "MS Dhoni, Indian cricket legend, unmistakable facial features, wicketkeeper pads and gloves, wearing number 7 blue jersey, iconic helicopter shot action, highly detailed sports portrait",
    "basketball": "professional basketball game, slam dunk action mid-air, hardwood court with glossy reflections, players jumping high, orange basketball, hoop and net, NBA style dynamic lighting",
    "phoenixsuns": "Phoenix Suns, purple and orange NBA jersey, sunburst logo, Footprint Center court, professional basketball action, fiery sun aesthetic",
    "milwaukeebucks": "Milwaukee Bucks, green and cream NBA jersey, deer logo, Fiserv Forum court, towering basketball players, intense slam dunk action",
    "michaeljordan": "Michael Jordan, unmistakable facial likeness, Chicago Bulls number 23 red jersey, iconic jumpman pose flying through the air, tongue out, basketball legend, slam dunk",
    "stephencurry": "Stephen Curry, accurate facial features, Golden State Warriors number 30 blue and yellow jersey, shooting a perfect three-pointer, splash brother, realistic NBA portrait",
    "goldenstatewarriors": "Golden State Warriors, blue and yellow NBA jersey, bridge logo, Chase Center court, fast-paced shooting basketball play, highly energetic sports scene",
    "superbowl": "Super Bowl championship game, American football action, massive stadium packed with fans, halftime show fireworks, silver Lombardi trophy, NFL authentic gear and helmets",
    "animal": "highly detailed wild animal, anatomical perfection, natural habitat environment, realistic fur/scales/feathers, extreme macro details, national geographic wildlife photography style",
    "lion": "majestic male African lion, massive thick golden mane framing a broad face, intense amber predator eyes, muscular feline build, lying in savanna or roaring showing canine teeth",
    "wolf": "wild gray wolf, thick coarse fur, pointed ears, piercing glowing yellow eyes, howling at the moon posture, snowy pine forest night, mysterious apex predator",
    "leopard": "spotted African leopard, distinctive rosette patterns on sleek golden fur, muscular feline build, resting stealthily on a thick tree branch, intense predatory gaze",
    "phoenix": "mythical phoenix bird, magnificent wingspan, glowing translucent fire feathers, rising from glowing embers and ash, majestic fantasy creature, intense magical flames",
    "pet": "cute domestic pet animal, incredibly soft fluffy fur, large adorable expressive eyes, cozy home interior environment, wholesome and heartwarming vibe, highly detailed",
    "dog": "clearly identifiable domestic dog (e.g. golden retriever), pronounced snout, floppy or perked ears, wagging tail, detailed fur texture, panting with visible tongue, distinct from felines",
    "cow": "massive heavy bovine dairy cow, large rectangular body, broad muzzle, black and white Holstein patches, small horns, standing on hooved legs in green pasture, distinct udder",
    "butterfly": "vibrant delicate butterfly, macro photography, intricate geometric patterns and scales on wings, resting on a brightly colored blooming flower, thin antennae",
    "dragon": "epic massive fantasy dragon, breathing thick roaring fire, heavily armored reptilian scales, huge leathery bat-like wings, flying over jagged mountains, mythical beast",
    "cat": "highly detailed feline cat, pointed triangular ears, long sensitive whiskers, small pink nose, vertical slit pupils, slender flexible body, padded paws with pink toe beans, retractable claws",
    "rabbit": "cute fluffy bunny rabbit, distinctively long ears, twitching nose, soft dense fur, small fluffy tail, eating a fresh carrot, sitting in a sunny spring garden",
    "panda": "giant panda bear, distinct black and white fur pattern, black patches around eyes, chubby round body, sitting and eating green bamboo stalks, lush bamboo forest",
    "bear": "massive wild grizzly bear, thick brown shaggy fur, powerful muscular build, catching a silver salmon fish in a splashing river, dense forest wilderness, apex predator",
    "hamster": "tiny adorable hamster, extremely chubby cheeks stuffed with food, holding a small sunflower seed in tiny paws, soft golden fur, macro photography of a cute pet",
    "fish": "vividly colorful tropical fish, intricate glowing scales, translucent fins, swimming gracefully in a vibrant coral reef, clear blue underwater photography, light rays through water",
    "bird": "beautiful wild avian bird, perched delicately on a thin tree branch, highly detailed colorful plumage and individual feathers, sharp beak, crisp nature photography",
    "eagle": "majestic bald eagle, striking white head and dark brown body, razor-sharp curved yellow beak, sharp massive talons, soaring through a clear blue sky, symbol of freedom",
    "tiger": "fierce Bengal tiger, unmistakable vivid orange fur broken by stark vertical black stripes, muscular heavy body, broad face with white accents, intense piercing predatory eyes",
    "unicorn": "magical majestic white horse with a single glowing spiraled horn on its forehead, flowing sparkling mane and tail, enchanted mystical forest background, epic fantasy art",
    "duck": "cute bright yellow duckling, soft fluffy down feathers, flat orange bill, swimming in a clear rippling pond, sunny day, adorable aquatic bird",
    "peacock": "majestic male peacock, displaying a massive fan of magnificent tail feathers, iridescent green and blue colors, intricate eye-spot patterns, elegant regal bird",
    "capybara": "chill capybara, giant rodent anatomy, boxy muzzle, coarse brown fur, relaxed peaceful expression, sitting in a hot spring bath with yellow yuzu fruits",
    "elephant": "massive African elephant, long prehensile trunk, huge floppy ears, long curved ivory tusks, thick wrinkled grey skin texture, dusty savanna environment, gentle giant",
    "pig": "cute little pink piglet, short legs, adorable flat snout, curly tail, smiling expression, standing in a small farm mud puddle, wholesome farm animal",
    "fox": "wild red fox, large bushy tail with a white tip, clever sharp eyes, pointed ears, standing in an autumn forest, vibrant orange fur contrasting with fallen leaves",
    "monkey": "playful primate monkey, long prehensile tail, expressive human-like face, nimble hands and feet, swinging on green vines in a dense tropical jungle",
    "penguins": "emperor penguin family, distinctive black and white tuxedo plumage with yellow neck accents, icy antarctic glacier landscape, waddling on thick snow, cute but resilient birds",
    "squirrel": "cute agile squirrel, massive bushy tail, holding an acorn in tiny front paws, sitting on a rough tree branch, soft fur, bright alert eyes",
    "horse": "majestic wild stallion horse, galloping powerfully in a dusty open field, highly muscular build, flowing mane and tail catching the wind, golden sunset lighting",
    "sheep": "fluffy domestic sheep, covered in extremely thick curly white wool, soft gentle face, grazing peacefully in a vast green meadow, idyllic farm scenery",
    "camel": "desert dromedary camel, distinct large single hump on its back, long neck, thick eyelashes protecting against sand, walking on sweeping golden sand dunes under a harsh sun",
    "universe": "vast awe-inspiring universe, glowing spiral galaxies, infinite sparkling stars, colorful cosmic dust nebulas, deep space exploration, majestic astronomical scale",
    "planet": "massive exoplanet in deep space, visible glowing atmosphere, intricate planetary rings made of ice and rock, orbiting a bright distant star, highly detailed sci-fi landscape",
    "astronaut": "human astronaut wearing a highly detailed, bulky white high-tech EVA spacesuit, reflective gold visor showing Earth, floating weightless in zero gravity outer space",
    "galaxy": "breathtaking spiral galaxy, vibrant cosmic colors blending purple, blue, and pink nebulae, millions of shining stars concentrated in a glowing core, Hubble telescope photography style",
    "spaceship": "massive futuristic sci-fi spaceship, complex metallic hull plating, glowing blue ion thrusters, cruising at warp speed through the dark cosmos, epic cinematic space opera",
    "aurora": "aurora borealis, magnificent northern lights, glowing ethereal green and purple ribbons dancing across the night sky, snowy mountain landscape below, magical atmospheric phenomenon",
    "game": "epic immersive video game scene, glowing RGB lighting aesthetic, action-packed digital world, highly detailed 3D rendering, first-person or third-person perspective",
    "gamepad": "modern ergonomic video game controller (like PS5 or Xbox), glowing buttons and thumbsticks, resting on a dark gamer desk with neon RGB background lighting, macro detail",
    "pubg": "PUBG battle royale realistic aesthetic, rugged character wearing iconic level 3 Spetsnaz helmet, holding a detailed assault rifle, standing in grassy Erangel map, survival grit",
    "minecraft": "Minecraft iconic blocky voxel world, character holding a pixelated diamond pickaxe, green creeper monster, lush green cubic biomes, 3D survival crafting aesthetic",
    "mario": "Super Mario iconic universe, Mario in red cap and blue overalls, jumping high over green warp pipes, colorful Mushroom Kingdom, floating gold coins, retro Nintendo gaming vibe",
    "leagueoflegends": "League of Legends champion in Summoner's Rift, epic fantasy MOBA battleground, intricate character armor, glowing magical ability effects, highly detailed splash art style",
    "jinx": "Jinx from Arcane/LoL, unmistakable long blue braided hair, chaotic manic energy, pale skin, holding her massive shark-shaped rocket launcher, neon green Zaun background",
    "valorant": "Valorant tactical shooter agent, stylish cel-shaded character design, holding a futuristic glowing Vandal or Phantom rifle, dynamic combat pose, clean esports aesthetic",
    "mortalkombat": "Mortal Kombat brutal fighter (like Scorpion), yellow ninja garb, glowing white eyes, throwing a metal chained kunai spear ('Get over here!'), dramatic lighting, hyper-realistic game render",
    "grandtheftauto": "GTA specific artwork style, urban Los Santos city landscape, luxury sports car, character holding a weapon with sunset palm trees, cinematic crime game illustration",
    "freefire": "Free Fire battle royale aesthetic, stylish tactical streetwear outfit, holding a glowing futuristic weapon, intense survival action, dynamic high-speed combat",
    "callofduty": "Call of Duty realistic soldier, modern warfare tactical gear, night vision goggles, camouflage uniform, gritty warzone battlefield, intense first-person shooter perspective",
    "genshinimpact": "Genshin Impact highly detailed gacha anime art style, colorful Teyvat fantasy landscape, character casting glowing elemental magic, intricate clothing designs",
    "halo": "Master Chief from Halo, iconic Spartan green power armor, gold reflective visor, holding a glowing blue energy sword, epic sci-fi ringworld background, legendary gaming hero",
    "hololive": "Hololive VTuber character, highly detailed anime girl aesthetic, colorful intricate idol outfit, streaming setup background with microphone, highly expressive cute face",
    "hollowknight": "Hollow Knight indie game art, small wandering bug knight wearing a pale mask and dark cloak, holding a nail weapon, dark gloomy beautifully atmospheric Hallownest background",
    "mobilelegends": "Mobile Legends Bang Bang (MLBB) champion, Land of Dawn background, epic fantasy MOBA hero design, dynamic glowing skill effects, highly saturated mobile game art",
    "arenaofvalor": "Arena of Valor (AOV) hero, epic massive fantasy armor, magical glowing battlegrounds, intense MOBA teamfight action, high-quality splash art",
    "naraka": "Naraka Bladepoint aesthetic, wuxia style ancient warrior, flowing martial arts robes, holding a grappling hook and katana, ancient Asian architecture, fluid combat motion",
    "film": "cinematic 8k movie poster, blockbuster film scene, dramatic dramatic studio lighting, perfect composition, sharp focus, IMAX quality visual storytelling",
    "dc": "DC Comics cinematic universe, dark and gritty aesthetic, towering gothic architecture of Gotham or Metropolis, legendary imposing superheroes, epic chiaroscuro lighting",
    "batman": "Batman the dark knight, highly detailed tactical batsuit with flowing black cape, pointed cowl, standing on a Gotham city gargoyle, raining night, glowing white eyes, brooding atmosphere",
    "theflash": "The Flash, sleek red speedster suit with lightning emblem, running at superhuman light speed, surrounded by intense yellow lightning trails, slow-motion distorted environment",
    "superman": "Superman the Man of Steel, iconic blue suit with red S-shield, majestic red cape flowing, flying high over Metropolis, warm sunlight beaming behind him, symbol of absolute hope",
    "joker": "The Joker, chaotic psychotic villain, messy green hair, purple suit, crazy manic smeared lipstick smile, dark gritty Gotham alleyway, terrifying psychological presence",
    "marvel": "Marvel Cinematic Universe aesthetic, epic Avengers superhero team-up, explosive action scene, highly detailed comic-book-inspired suits, blockbuster CGI effects",
    "spiderman": "Spider-Man, iconic red and blue webbed suit, white expressive eye lenses, swinging dynamically on a web through towering New York City skyscrapers, acrobatic pose",
    "wolverine": "Wolverine (Logan), fierce angry expression, indestructible adamantium claws extended from knuckles, yellow and blue X-Men suit or white tank top, battle-damaged and bloody",
    "deadpool": "Deadpool, merc with a mouth, textured red and black tactical suit, white expressive eyes on mask, holding dual katanas, comedic action pose breaking the fourth wall",
    "thanos": "Thanos the mad titan, massive muscular purple alien figure, wearing the golden Infinity Gauntlet with 6 glowing infinity stones, imposing and inevitable cosmic villain",
    "blackpanther": "Black Panther (T'Challa), sleek high-tech black vibranium suit with silver claw accents, Wakanda forever crossed-arms pose, glowing purple kinetic energy aura",
    "captainmarvel": "Captain Marvel (Carol Danvers), binary form, glowing blinding cosmic aura, eyes glowing white, flying through space destroying ships, powerful superheroine",
    "ghostrider": "Ghost Rider, terrifying flaming skull head, black leather biker jacket with spikes, riding a massive chopper motorcycle engulfed in hellfire, dark supernatural anti-hero",
    "scarletwitch": "Scarlet Witch (Wanda Maximoff), wearing the dark red intricate tiara and costume, fingers glowing with intense red chaos magic, floating ominously, darkhold corruption",
    "thor": "Thor the God of Thunder, muscular Asgardian build, holding the Mjolnir hammer, massive lightning bolts striking down, silver armor and red cape, epic thunder storm background",
    "ironman": "Iron Man (Tony Stark), highly detailed sleek red and gold high-tech mechanical armor, glowing blue arc reactor in chest, flying using repulsor blasts from hands and boots",
    "venom": "Venom the alien symbiote, massive terrifying muscular figure, insanely long prehensile tongue, rows of razor-sharp teeth, black gooey liquid texture, menacing anti-hero",
    "captainamerica": "Captain America (Steve Rogers), iconic star-spangled blue uniform, holding the circular vibranium shield with red white and blue rings, heroic leadership stance",
    "hulk": "The Incredible Hulk, massive unnaturally huge green muscular giant, roaring in absolute uncontrollable rage, smashing the concrete ground, ripped purple pants",
    "gameofthrones": "Game of Thrones dark fantasy aesthetic, Westeros landscape, the imposing iron throne made of melted swords, massive fire-breathing dragons flying, medieval political tension",
    "wukong": "Sun Wukong the Monkey King, Black Myth aesthetic, holding the Ruyi Jingu Bang staff, intricate ancient Chinese armor, standing defiantly on a cloud, monkey features",
    "it": "IT movie horror aesthetic, a single floating red balloon, rainy dreary street, creepy dark storm drain sewer grate, Derry town, terrifying supernatural dread",
    "pennywise": "Pennywise the dancing clown, terrifying sinister smile, glowing yellow eyes, cracked white face makeup, Victorian clown suit, holding a red balloon, ultimate horror villain",
    "frankenstein": "Frankenstein's monster, towering undead creature, sickly green stitched skin, metallic neck bolts, dark gothic horror laboratory background, dramatic lightning strike",
    "zombie": "undead walking zombie, gruesome decaying rotting flesh, tattered bloody clothes, glowing or dead eyes, post-apocalyptic ruined city background, horror survival nightmare",
    "ghostface": "Ghostface killer from the Scream franchise, iconic elongated white screaming mask, flowing black hooded robe, holding a bloody hunting knife, meta slasher horror",
    "fridaythe13th": "Friday the 13th classic slasher atmosphere, Camp Crystal Lake sign, dark foggy terrifying pine woods at midnight, absolute horror isolation",
    "jasonvoorhees": "Jason Voorhees, towering unstoppable killer, wearing a worn dirt-stained hockey mask, holding a massive bloody machete, standing silently in dark woods",
    "theaddamsfamily": "The Addams Family gothic comedy aesthetic, spooky decrepit Victorian mansion, Wednesday Addams pale deadpan expression, creepy kooky and mysterious vibe",
    "scream": "Scream movie suspenseful slasher aesthetic, 1990s horror film vibe, terrifying phone call, killer lurking in the shadows of a suburban house",
    "michaelmyers": "Michael Myers from Halloween, pale expressionless William Shatner mask, dark blue mechanic coveralls, holding a large chef's knife, silent unstoppable stalker",
    "chucky": "Chucky the killer possessed doll, Good Guys colorful overalls and striped shirt, stitched scarred face, red hair, holding a massive kitchen knife, creepy horror toy",
    "dracula": "Count Dracula the classic vampire, slicked black hair, pale skin, sharp fangs, long black cape with blood-red lining, standing in a gothic Transylvanian castle",
    "oppenheimer": "Oppenheimer movie cinematic style, intense dramatic portrait, 1940s vintage aesthetic, atomic bomb mushroom cloud explosion reflecting in his glasses, historical weight",
    "dune": "Dune movie epic sci-fi aesthetic, vast Arrakis golden desert landscape, massive terrifying sandworm erupting from the sand, Paul Atreides with glowing blue spice eyes",
    "beetlejuice": "Beetlejuice, wild messy green hair, iconic black and white vertically striped suit, pale face with dark eye makeup, Tim Burton gothic comedy style, creepy and wacky",
    "theironclaw": "The Iron Claw movie aesthetic, Von Erich family professional wrestling, 1980s vintage sports photography, muscular wrestlers in the ring, intense emotional sports drama",
    "gundam": "Mobile Suit Gundam, giant highly detailed mecha robot, intricate mechanical joints, iconic v-fin antenna, epic space battle, glowing beam saber, high-tech Japanese sci-fi",
    "kpopdemonhunter": "K-pop idol visually designed as a demon hunter, highly stylish black tech-wear, attractive facial features, holding a glowing magical weapon, dark urban fantasy setting",
    "lokahchapter1chandra": "epic fantasy adventure visual, Chandra character design, wielding mystical glowing powers, detailed lore-rich ancient environment, high fantasy concept art",
    "strangerthings": "Stranger Things 1980s retro sci-fi horror aesthetic, the dark Upside Down dimension, floating spores, glowing red lightning, terrifying Demogorgon monster, kids on BMX bikes",
    "predator": "The Predator, terrifying Yautja alien hunter, dreadlock-like appendages, high-tech metallic biomask, shoulder-mounted plasma cannon, invisible cloaking distortion in deep jungle",
    "nowyouseeme": "Now You See Me movie aesthetic, grand illusionist magic show, glowing floating playing cards, mysterious magicians in sharp suits, dynamic stage lighting and crowd",
    "theboys": "The Boys dark gritty superhero satire, Homelander with a terrifying fake smile and glowing red laser eyes, realistic comic book style, violent and cynical atmosphere",
    "avatar": "Avatar movie Pandora landscape, glowing bioluminescent alien jungle, tall blue Na'vi character, floating Hallelujah mountains in the sky, visually stunning 3D CGI masterpiece",
    "godzilla": "Godzilla, King of the Monsters, colossal reptilian kaiju, glowing bright blue dorsal plates charging up atomic breath, destroying a rainy neon-lit metropolis",
    "kingkong": "King Kong, giant massive angry silverback gorilla, beating his heavily muscled chest, roaring fiercely, standing on top of a towering city skyscraper, MonsterVerse scale",
    "cartoon": "classic 2D animated cartoon style, highly vibrant flat colors, exaggerated expressive characters, thick outlines, nostalgic joyful television animation aesthetic",
    "theamazingworldofgumball": "The Amazing World of Gumball style, unique mixed media animation combining 2D characters with photorealistic backgrounds, bright colorful surreal weird world",
    "gumballwatterson": "Gumball Watterson, 2D animated blue cat character, wearing a tan sweater and grey pants, funny exaggerated facial expression, cartoon network style",
    "darwinwatterson": "Darwin Watterson, 2D animated orange goldfish with legs, wearing green sneakers, innocent happy expression, cartoon network style",
    "familyguy": "Family Guy adult animated sitcom style, Quahog town background, simple 2D character designs, flat coloring, specific distinct facial drawing style",
    "petergriffin": "Peter Griffin, fat cartoon man, wearing glasses, white shirt and green pants, distinct cleft chin, laughing loudly, Family Guy style",
    "stewiegriffin": "Stewie Griffin, evil genius cartoon baby, football-shaped head, wearing yellow shirt and red overalls, holding a high-tech ray gun, Family Guy style",
    "briangriffin": "Brian Griffin, anthropomorphic white talking dog, wearing a red collar, holding a martini glass, intellectual expression, Family Guy style",
    "glennquagmire": "Glenn Quagmire, cartoon man with an oversized jaw, wearing a red hawaiian shirt, iconic 'giggity' expression, Family Guy style",
    "clevelandbrown": "Cleveland Brown, calm expression cartoon man, curly hair and mustache, wearing a yellow shirt, Family Guy style",
    "joeswanson": "Joe Swanson, muscular cartoon police officer sitting in a wheelchair, intense angry screaming face, large chin, Family Guy style",
    "thesimpsons": "The Simpsons classic 2D animation style, characters with distinct yellow skin, big bulging eyes, overbites, Springfield town background",
    "bartsimpson": "Bart Simpson, yellow skin cartoon kid, spiky hair, wearing a red shirt, riding a skateboard, eating a squishee, mischievous expression",
    "natra": "Nezha (Na Tra), Chinese mythology 3D donghua character, fierce child deity, dark eyeliner, holding the glowing fire-tipped spear, standing on wind fire wheels",
    "aobing": "Ao Bing, Chinese mythology dragon prince, highly elegant, long flowing blue and white robes, beautiful pale features, manipulating ice magic, 3D donghua style",
    "disney": "Disney and Pixar high-end 3D animation style, incredibly expressive characters with large eyes, magical atmosphere, hyper-detailed hair and clothing textures, beautiful cinematic lighting",
    "insideout": "Inside Out movie aesthetic, glowing colorful emotion characters inside the high-tech mind headquarters console, colorful Pixar 3D art style",
    "coco": "Coco movie aesthetic, Disney Pixar, vibrant colorful Dia de los Muertos festival, glowing orange marigold bridge, detailed skeleton musician playing guitar",
    "zootopia": "Zootopia movie aesthetic, modern bustling city populated entirely by anthropomorphic animals, Judy Hopps the bunny cop and Nick Wilde the fox, Disney 3D style",
    "baymax": "Baymax from Big Hero 6, large white inflatable healthcare robot, extremely cute and huggable minimal design, dot-and-line eyes, high-tech San Fransokyo background",
    "spongebob": "SpongeBob SquarePants, classic 2D cartoon, yellow porous sponge character wearing square pants and tie, underwater Bikini Bottom pineapple house background",
    "peanuts": "Peanuts classic comic strip and cartoon style, Snoopy the white beagle and Charlie Brown, simple minimalist ink lines, warm classic nostalgia",
    "bighero6": "Big Hero 6 movie aesthetic, San Fransokyo city blending Japanese and American architecture, neon lights, high-tech teenage superhero team, Disney 3D animation",
    "tomandjerry": "Tom and Jerry classic retro animation, slapstick comedy chase sequence, Tom the grey cat trying to catch Jerry the small brown mouse, highly exaggerated motion",
    "ben10": "Ben 10 animated series, Ben Tennyson teenager wearing the glowing green Omnitrix watch, transforming into a glowing green alien, Cartoon Network action aesthetic",
    "bugsbunny": "Bugs Bunny, iconic Looney Tunes grey rabbit, casually chewing on a carrot, 'What's up doc?' smug expression, classic golden age cartoon style",
    "stitch": "Stitch (Experiment 626) from Lilo & Stitch, small blue alien, big ears, cute but highly destructive expression, lush Hawaiian tropical beach background",
    "sonic": "Sonic the Hedgehog, iconic blue anthropomorphic hedgehog, running at super supersonic speed creating a blue blur, collecting glowing gold rings, SEGA mascot",
    "minions": "Minions from Despicable Me, small yellow pill-shaped creatures, wearing thick metal goggles and blue denim overalls, laughing chaotically, Illumination 3D style",
    "paddington": "Paddington Bear, incredibly cute and polite 3D animated bear, wearing a floppy red hat and blue duffle coat, eating a marmalade sandwich, London street background",
    "nightmarebeforechristmas": "The Nightmare Before Christmas aesthetic, Tim Burton stop-motion claymation style, spooky crooked Halloween Town architecture, gothic creepy-cute vibe",
    "jackskellington": "Jack Skellington the Pumpkin King, tall incredibly thin skeleton wearing a black and white pinstripe suit, spooky graveyard background, Tim Burton stop-motion style",
    "howtotrainyourdragon": "How to Train Your Dragon 3D aesthetic, Toothless the extremely cute black Night Fury dragon, flying rapidly through thick white clouds, Viking island of Berk",
    "kungfupanda": "Kung Fu Panda 3D aesthetic, Po the giant panda dragon warrior, performing a dynamic martial arts pose, wearing patchwork shorts, ancient China majestic background",
    "pocoyo": "Pocoyo children's cartoon, 3D toddler character wearing entirely blue clothes and hat, absolutely pure white background, simple colorful shapes, cute educational aesthetic",
    "metroman": "Metro Man from Megamind, exaggerated hyper-masculine 3D superhero, massive chin, glowing white outfit with cape, floating with an arrogant confident smile",
    "avatarthelastairbender": "Avatar The Last Airbender animated series style, epic Asian martial arts fantasy, character bending the four glowing elements (water, earth, fire, air), dynamic action",
    "walle": "WALL-E, small boxy trash-compacting robot, rusty metal textures, extremely expressive binocular eyes, delicately holding a single green plant in a boot, dystopian ruined Earth",
    "iceage": "Ice Age 3D movie aesthetic, Scrat the saber-toothed squirrel desperately chasing a single acorn, massive snowy prehistoric glacier landscape",
    "regularshow": "Regular Show animated series, Mordecai the blue jay and Rigby the raccoon, surreal cartoon network sitcom aesthetic, slacker vibe in a city park background",
    "couragethecowardlydog": "Courage the Cowardly Dog, small pink beagle dog, screaming in absolute exaggerated cartoon terror, creepy isolated Nowhere farmhouse background, unsettling 2D style",
    "adventuretime": "Adventure Time animated style, Land of Ooo, highly colorful surreal fantasy world, 2D flat vector cartoon, noodle-like limbs, whimsical but weird",
    "finn": "Finn the Human, Adventure Time style, wearing a distinctive white animal hat and blue shirt, holding a golden sword, ready for an epic heroic adventure",
    "jake": "Jake the Dog, Adventure Time style, yellow stretchy magical bulldog, huge cartoon eyes, morphing his body into a giant fist",
    "marceline": "Marceline the Vampire Queen, Adventure Time style, long black hair, pale skin, floating in the air, playing her signature red axe bass guitar",
    "princessbubblegum": "Princess Bubblegum, Adventure Time style, entirely pink character with long pink bubblegum hair, wearing a golden crown and a white science lab coat",
    "iceking": "Ice King, Adventure Time style, crazy old wizard with a massive long white beard, wearing a glowing magical crown and blue tunic, casting blue ice magic",
    "bmo": "BMO, Adventure Time style, extremely cute living teal game console character, expressive digital face on screen, holding a game controller",
    "gunter": "Gunter the penguin, Adventure Time style, cute simple 2D penguin design, black and white, secretly harboring an evil cosmic entity",
    "rickandmorty": "Rick and Morty animated sitcom style, mad scientist Rick and nervous Morty, stepping through a swirling glowing green portal, bizarre sci-fi comedy aesthetic",
    "webarebears": "We Bare Bears modern cartoon style, Grizzly, Panda, and Ice Bear uniquely stacked on top of each other, cute wholesome urban background",
    "toystory": "Toy Story Disney Pixar 3D aesthetic, Woody the cowboy and Buzz Lightyear the space ranger, highly detailed living plastic and fabric toys, massive Andy's room background",
    "anime": "high-quality anime visual style, studio Ufotable or MAPPA animation quality, intricate detailed cel shading, highly vibrant 2D illustration, beautiful Japanese aesthetic",
    "dragonball": "Dragon Ball Z iconic anime aesthetic, highly muscular characters, spiky defying-gravity hair, intense glowing energy auras, Akira Toriyama sharp art style, martial arts combat",
    "goku": "Goku, Super Saiyan form, glowing spiky golden hair, intense radiating golden energy aura, charging a bright blue Kamehameha wave, battle-damaged orange gi",
    "vegeta": "Vegeta, the proud Prince of all Saiyans, arrogant aggressive smirk, widows peak spiky black hair, wearing blue saiyan armor, firing a purple Galick Gun beam",
    "frieza": "Frieza, final form, sleek white and purple alien emperor, cold menacing villainous expression, holding a massive glowing red death ball energy attack",
    "gohan": "Gohan, Super Saiyan 2 form, fierce crying determination, spiky blonde hair with a single bang, intense blue electric sparks in aura, wearing Piccolo's purple gi",
    "piccolo": "Piccolo, tall Namekian warrior, green skin with pink patches, wearing a heavy white weighted cape and turban, pointing two fingers charging a spiraling Special Beam Cannon",
    "trunks": "Future Trunks, purple hair, wearing a blue Capsule Corp crop jacket, holding a sharp steel broadsword, extremely serious and desperate expression, apocalyptic background",
    "majinbuu": "Majin Buu, fat pink alien blob creature, closed eyes and wide smile, wearing white pants and a black M belt, steam blowing out of holes in his head",
    "onepiece": "One Piece anime style, Grand Line ocean background, epic shonen pirate adventure, highly unique exaggerated character designs, Eiichiro Oda art style",
    "luffy": "Monkey D. Luffy, Gear 5 form, laughing maniacally, glowing white hair and clothes, wearing a straw hat, stretching rubber body dynamically, cartoonish god-like power",
    "sanji": "Sanji, blonde hair covering one eye, wearing a sharp black suit, holding a lit cigarette, kicking dynamically with a blazing fiery leg (Diable Jambe technique)",
    "chopper": "Tony Tony Chopper, incredibly cute small reindeer doctor, blue nose, wearing a big pink top hat with a white cross, One Piece mascot",
    "ace": "Portgas D. Ace, muscular shirtless pirate, black hair, wearing an orange cowboy hat, manipulating massive glowing orange fire from his hands, One Piece",
    "zoro": "Roronoa Zoro, muscular swordsman, green hair, glowing red eye, iconic three-sword style (one sword in mouth, two in hands), epic devastating samurai slash aura",
    "animeboy": "handsome attractive anime boy, detailed expressive eyes, trendy modern clothing, cool aloof aesthetic, shoujo manga romance style, soft beautiful lighting",
    "animegirl": "beautiful anime girl (waifu), long flowing detailed hair, expressive big sparkling eyes, kawaii aesthetic, cute blushing expression, highly detailed lighting and shading",
    "jujutsukaisen": "Jujutsu Kaisen dark fantasy anime style, MAPPA studio high-quality animation, dark gritty urban setting, intense glowing cursed energy effects, dynamic camera angles",
    "yujiitadori": "Yuji Itadori, pink spiky hair, wearing the dark blue Jujutsu High uniform with red hood, glowing blue cursed energy wrapping around his fists, dynamic martial arts punch",
    "ryomensukuna": "Ryomen Sukuna, the terrifying King of Curses, evil arrogant smirk, black tattoos covering his face and body, sitting menacingly on a massive throne of human skulls",
    "megumifushiguro": "Megumi Fushiguro, spiky black hair, intense focused expression, making hand signs to summon dark ink-like shadow shikigami (divine dogs), Jujutsu Kaisen",
    "tojifushiguro": "Toji Fushiguro, extremely muscular imposing figure, tight black shirt, terrifying confident assassin, holding the bizarre Inverted Spear of Heaven weapon",
    "getosuguru": "Suguru Geto, villainous Jujutsu sorcerer, wearing traditional Japanese monk robes, hair tied in a bun, surrounded by terrifying grotesque cursed spirits",
    "satorugojo": "Satoru Gojo, wearing a black blindfold, pure white spiky hair, lowering blindfold to reveal glowing blue Six Eyes, casting the destructive Hollow Purple glowing orb",
    "narutoshippuden": "Naruto Shippuden anime style, Japanese ninja shinobi aesthetic, Hidden Leaf Village background, epic martial arts combat, spectacular glowing jutsu elemental effects",
    "sasuke": "Sasuke Uchiha, dark emo ninja clothes, one eye glowing red Sharingan, one eye purple Rinnegan, holding a sparking blue Chidori lightning blade in his hand",
    "uzumakinaruto": "Uzumaki Naruto, Kurama Nine-Tails chakra mode, entire body glowing with intense orange and yellow fire-like aura, holding a swirling blue Rasengan sphere",
    "sharingan": "Sharingan eye, extreme macro close-up, glowing blood red, three black tomoe spinning around the pupil, Naruto ocular jutsu, intense magical eye",
    "itachi": "Itachi Uchiha, wearing the iconic black Akatsuki cloak with red clouds, cold emotionless gaze, glowing red Mangekyou Sharingan, surrounded by a flock of black crows",
    "kakashi": "Kakashi Hatake, silver spiky hair, face mask covering his mouth, ninja headband tilted to cover one eye, reading a small orange book, relaxed but deadly ninja",
    "hinata": "Hinata Hyuga, dark blue hair, pure white Byakugan eyes with veins bulging, gentle fist martial arts stance, kind but determined expression, Naruto shippuden",
    "jiraiya": "Jiraiya the legendary toad sage, massive spiky white hair, red war paint lines running down his eyes, standing triumphantly on top of a giant smoking toad",
    "sakura": "Sakura Haruno, pink hair, concentrating massive chakra into a single devastating punch, shattering the rocky ground into pieces, fierce determined kunoichi",
    "garaa": "Gaara of the Sand, red hair, red kanji symbol for 'love' on his forehead, cold gaze, manipulating massive amounts of floating sand from a gourd on his back",
    "madara": "Madara Uchiha, epic god-like villain, long wild black hair, red samurai armor, massive towering blue Susanoo spectral warrior aura forming behind him",
    "crayonshinchan": "Crayon Shin-chan (Shinnosuke Nohara), extremely simple 2D cartoon style, potato-shaped head, funny mischievous 5-year-old kid, thick eyebrows",
    "shinchan": "Shin-chan, wearing his iconic red t-shirt and yellow shorts, doing a funny inappropriate dance, classic Japanese nostalgic comedy anime",
    "sanrio": "Sanrio highly cute aesthetic, pastel color palette, super kawaii universe, simple rounded character designs, extremely wholesome and soft vibe",
    "hellokitty": "Hello Kitty, iconic white cartoon cat, wearing a bright red or pink bow on her left ear, no mouth, extremely cute minimalist design, pastel pink background",
    "kuromi": "Kuromi, cheeky mischievous white rabbit character, wearing a black jester hat with a pink skull on the front, devil tail, gothic kawaii aesthetic",
    "demonslayer": "Demon Slayer (Kimetsu no Yaiba) anime style, Ufotable studio animation, incredibly stunning glowing elemental sword breathing effects, Taisho era Japan aesthetic",
    "tanjirokamado": "Tanjiro Kamado, green and black checkered haori, hanafuda earrings, holding a black katana, executing a stunning glowing blue water breathing water dragon slash",
    "nezukokamado": "Nezuko Kamado, cute demon girl, wearing a pink kimono, a green bamboo muzzle in her mouth, shrinking to a small adorable size, Demon Slayer",
    "shinobu": "Shinobu Kocho, Insect Hashira, beautiful butterfly hairpiece, wearing a butterfly wing haori, holding a thin elegant purple poison sword, beautiful but deadly smile",
    "rengoku": "Kyojuro Rengoku, Flame Hashira, wild fiery yellow hair with red tips, wildly enthusiastic wide-eyed smile, executing a massive blazing fire breathing sword slash",
    "akaza": "Akaza, Upper Rank Three demon, pink hair, intricate blue line tattoos covering his pale skin, martial arts combat stance, glowing blue compass needle technique on the ground",
    "zenitsuagatsuma": "Zenitsu Agatsuma, blonde hair, asleep while standing, executing Thunder Breathing First Form, entire body surrounded by blindingly fast glowing yellow lightning",
    "inosukehashibira": "Inosuke Hashibira, highly muscular shirtless boy wearing a hollowed-out grey boar head as a mask, dual-wielding heavily jagged chipped katanas, wild beast posture",
    "dandadan": "Dandadan manga/anime style, supernatural action, incredibly crazy chaotic perspective, blending terrifying ghosts with sci-fi aliens, high-octane energy",
    "kentakakura": "Okarun from Dandadan, transformed state, white hair, creepy black mask-like face, turbo granny powers, incredibly fast creepy movement, supernatural action",
    "tsubasajinnouchi": "Momo Ayase from Dandadan, school uniform, psychic powers, controlling massive invisible aura hands, intense dynamic manga panel composition",
    "blackclover": "Black Clover anime style, Asta, highly muscular short boy, holding a massive rusty anti-magic Demon-Slayer sword, glowing black and red demonic energy, intense screaming",
    "pokemon": "Pokemon franchise aesthetic, highly vibrant colors, catching cute and powerful pocket monsters, official Nintendo art style, nostalgic anime adventure",
    "charmande": "Charmander, extremely cute orange bipedal lizard pokemon, a bright warm fire burning on the very tip of its tail, happy expression",
    "pikachu": "Pikachu, iconic electric mouse pokemon, bright yellow fur, red circles on cheeks, lightning bolt-shaped tail, sparking bright yellow electricity",
    "cubone": "Cubone, small brown dinosaur-like pokemon, wearing a white skull as a helmet covering its face, holding a small bone club, lonely but cute aesthetic",
    "bulbasaur": "Bulbasaur, small quadruped dinosaur pokemon, teal-green skin with dark spots, carrying a large green plant bulb on its back, cute wide smile",
    "gengar": "Gengar, dark purple round ghost pokemon, extremely sinister wide grinning smile, glowing red eyes, hiding in a spooky dark shadow, Halloween vibe",
    "squirtle": "Squirtle, cute blue bipedal turtle pokemon, brown shell, shooting a stream of water from its mouth, sometimes wearing cool pointy black sunglasses",
    "psyduck": "Psyduck, yellow bipedal duck pokemon, holding its head with its hands in constant confusion, suffering from a psychic headache, very funny expression",
    "sailormoon": "Sailor Moon (Usagi Tsukino), iconic magical girl transformation sequence, blonde hair in odango twin tails, sailor fuku uniform, sparkling pastel cosmic background, 90s retro anime",
    "thegodofhighschool": "The God of High School anime/webtoon style, epic hyper-fast martial arts combat, dynamic fluid animation, high school tournament setting, glowing divine powers",
    "jinmori": "Jin Mori, Monkey King form, extending the massive Yeoui staff, executing a devastating Taekwondo high kick, blue dragon aura, epic webtoon action",
    "sakamotodays": "Sakamoto Days manga style, Taro Sakamoto, chubby older man wearing a red convenience store apron and glasses, executing flawless John Wick-style assassin combat",
    "haikyu": "Haikyuu!! sports anime style, highly intense high school volleyball match, extreme dynamic angles, characters jumping incredibly high for a spike, realistic shiny sweat drops",
    "shoyohinata": "Shoyo Hinata, bright orange messy hair, jumping unbelievably high over the volleyball net, preparing to spike the ball, intense focus in his eyes, Haikyuu",
    "tobiokageyama": "Tobio Kageyama, black hair, setting the volleyball with absolute god-like precision, intense intimidating aura, the 'King of the Court', Haikyuu",
    "swordartonline": "Sword Art Online (SAO) anime style, virtual reality MMORPG aesthetic, floating Aincrad castle background, glowing intricate UI interfaces, epic fast-paced sword fight",
    "asuna": "Asuna Yuuki, beautiful long chestnut hair, wearing the red and white Knights of the Blood Oath uniform, holding a silver rapier, executing lightning-fast thrusts, SAO",
    "alice": "Alice Zuberg from SAO Alicization, beautiful blonde knight, wearing heavy golden armor, holding the glowing Fragrant Olive Sword turning into golden flower petals",
    "ghibli": "Studio Ghibli iconic art style, Hayao Miyazaki, incredibly lush detailed watercolor backgrounds, magical realism, nostalgic peaceful deeply atmospheric animation",
    "totoro": "My Neighbor Totoro, giant extremely fluffy friendly grey forest spirit, holding a small leaf umbrella while standing in the pouring rain, cute Studio Ghibli magic",
    "spiritedaway": "Spirited Away movie aesthetic, Chihiro running through a highly magical bustling spirit world, mysterious towering traditional Japanese bathhouse background, Ghibli",
    "ponyo": "Ponyo, incredibly cute magical fish-girl with red hair, running enthusiastically on top of giant undulating blue ocean waves shaped like fish, Studio Ghibli art",
    "bluelock": "Blue Lock anime style, incredibly intense soccer manga aesthetic, characters with glowing intensely focused eyes, glowing puzzle pieces aura, extreme egoist striker combat",
    "kurokonobasket": "Kuroko's Basketball anime style, characters entering the glowing 'Zone', extreme supernatural basketball moves, high-speed sports action, intense colored eye trails",
    "darlinginthefranxx": "Darling in the FranXX anime style, highly futuristic mecha robot combat, post-apocalyptic world, teenagers in tight pilot suits, neon glowing interfaces",
    "zerotwo": "Zero Two, beautiful anime waifu, long pink hair, cute small red horns on her forehead, wearing a skin-tight red pilot suit, confident and slightly crazy smile",
    "myheroacademia": "My Hero Academia anime style, 'Plus Ultra', superhero high school students, vibrant comic book shading, epic glowing 'Quirk' superpower effects",
    "izuku": "Izuku Midoriya (Deku), green messy hair, One For All Full Cowl, entire body crackling with glowing green lightning, delivering a massive heroic punch",
    "himikotoga": "Himiko Toga, messy blonde hair in twin buns, crazy psychotic yandere smile with fangs, wearing a school uniform and villain gear, holding a bloody knife",
    "chainsawman": "Chainsaw Man anime style, incredibly dark gritty urban fantasy, massive amounts of blood and gore, cinematic MAPPA studio lighting, chaotic insane battles",
    "denji": "Denji transformed into Chainsaw Man, a terrifying bloody chainsaw protruding from his head and both arms, revving engine cord on chest, brutally slicing through demons",
    "slamdunk": "Slam Dunk classic 90s retro anime style, highly realistic basketball anatomy, intense emotional high school match, Takehiko Inoue legendary manga art",
    "conan": "Detective Conan (Case Closed), Edogawa Conan, small boy wearing glasses and a blue suit with red bowtie, pointing his finger confidently solving a murder mystery",
    "doraemon": "Doraemon, iconic round blue robot cat from the 22nd century, no ears, wearing a small bamboo copter on his head, pulling a gadget from his 4D pocket, classic anime",
    "sololeveling": "Solo Leveling webtoon style, high-quality dark epic fantasy, glowing blue floating system UI screens, terrifying shadow monsters, incredibly badass power fantasy",
    "sungjinwoo": "Sung Jin-Woo, Shadow Monarch, glowing blue eyes, holding dual magical daggers, commanding a massive terrifying army of black and blue shadow soldiers",
    "bleach": "Bleach anime style, Shinigami (Soul Reapers), Soul Society traditional Japanese architecture, terrifying Hollow masks, epic Zanpakuto sword releases, Tite Kubo sharp art style",
    "ichigokurosaki": "Ichigo Kurosaki, Bankai form, wearing a long ragged black coat, holding the sleek black Zangetsu sword, unleashing a massive black and red Getsuga Tensho energy blast",
    "toshirohitsugaya": "Toshiro Hitsugaya, young white-haired captain, executing Daiguren Hyorinmaru, massive detailed ice dragon wings and tail attached to his body, freezing cold aura",
    "shihouinyoruichi": "Yoruichi Shihoin, dark-skinned Flash Goddess, executing Shunko, back and shoulders surrounded by intense glowing white lightning aura, hand-to-hand combat stance",
    "aizensosuke": "Sosuke Aizen, slicked-back brown hair, wearing white Arrancar clothes, incredibly arrogant god-complex smile, crushing his glasses, ultimate mastermind Bleach villain",
    "ranma": "Ranma 1/2 classic Rumiko Takahashi anime style, 90s nostalgic comedy aesthetic, martial arts training, characters transforming with cold/hot water",
    "worldtrigger": "World Trigger anime style, sci-fi tactical squad battle, characters holding futuristic glowing Trion weapons, highly geometric glowing green cubes environment",
    "frieren": "Frieren: Beyond Journey's End, incredibly beautiful elven mage, twin-tail white hair, casting a glowing intricate magical spell, peaceful highly detailed fantasy landscape",
    "spyxfamily": "Spy x Family anime style, wholesome but chaotic fake family, 1960s retro spy aesthetic, elegant fashion, comedy and action blended beautifully",
    "loidforger": "Loid Forger (Twilight), incredibly handsome tall spy, wearing a sharp three-piece green suit, holding a silenced pistol, cool and calculating expression",
    "anyaforger": "Anya Forger, small cute girl with pink hair, iconic extremely smug 'heh' facial expression, reading minds, holding a bag of peanuts, Spy x Family",
    "yorforger": "Yor Forger (Thorn Princess), beautiful but deadly assassin, wearing a highly elegant black dress with red roses, holding dual golden stiletto weapons",
    "rezero": "Re:Zero - Starting Life in Another World, dark psychological isekai fantasy, beautiful magic effects contrasting with brutal horrific deaths and suffering",
    "ram": "Ram, cute anime maid, short pink hair covering one eye, highly sarcastic and condescending expression, holding a cleaning mop, Re:Zero",
    "rem": "Rem, beautiful anime maid waifu, short blue hair covering one eye, holding a massive deadly chained morningstar weapon, incredibly sweet and loyal expression, Re:Zero",
    "subaru": "Natsuki Subaru, wearing a black, white, and orange tracksuit, experiencing Return by Death, extreme psychological suffering and terror on his face, Re:Zero",
    "attackontitan": "Attack on Titan (Shingeki no Kyojin) anime style, towering terrifying naked flesh Titans, walled medieval city, soldiers using vertical maneuvering equipment, MAPPA gritty style",
    "leviackerman": "Levi Ackerman, incredibly fast, wearing Survey Corps green cape, holding dual ultrahard steel blades, spinning like a deadly top slicing a Titan's nape, intense cold eyes",
    "erenyeager": "Eren Yeager, Attack Titan form, massive muscular 15-meter giant, roaring with pure fury, glowing green eyes, jaw unhinged, dark gritty and bloody",
    "oshinoko": "Oshi no Ko anime style, Japanese idol culture, characters with incredibly detailed glowing starry eyes, gorgeous highly colorful stage lights, dark dramatic shadows",
    "fullmetalalchemist": "Fullmetal Alchemist: Brotherhood anime style, glowing intricate alchemy transmutation circles, bright blue alchemical electricity, steampunk automail limbs, epic fantasy",
    "mobpsycho100": "Mob Psycho 100 anime style, Mob reaching 100% psychic explosion, incredibly chaotic colorful fluid animation, surreal terrifying psychic powers warping reality",
    "overlord": "Overlord anime style, Ainz Ooal Gown, giant terrifying skeletal lich, wearing majestic purple and gold robes, glowing red orbs in eye sockets, supreme ruler of Nazarick",
    "fate": "Fate/Stay Night anime style, Holy Grail War, incredibly beautiful Ufotable studio animation, epic high-speed heroic spirit fight scenes, brilliant glowing Noble Phantasm clashes",
    "saber": "Saber (Artoria Pendragon), beautiful blonde knight, wearing a blue dress with silver armor, holding the glowing holy sword Excalibur, brilliant holy light, Fate series",
    "hunterxhunter": "Hunter x Hunter anime style, epic shonen battles, characters using complex glowing Nen aura, Yoshihiro Togashi distinct character designs and manga art",
    "humans": "highly realistic human portrait, cinematic lighting, raw DSLR photography, incredibly detailed facial features, visible skin pores and texture, 8k resolution perfection",
    "kpop": "K-pop idol highly stylized aesthetic, spectacular stage performance, massive glowing concert lights, trendy fashionable high-end outfits, synchronized attractive dancing",
    "bigbang": "BIGBANG legendary K-pop group, intense hip-hop stage presence, yellow crown-shaped lightsticks, massive glowing yellow ocean crowd, highly charismatic performance",
    "bts": "BTS K-pop global superstars, synchronized perfect dancing, holding microphones, Army Bomb spherical lightsticks, massive stadium concert, incredibly stylish designer outfits",
    "blackpink": "BLACKPINK K-pop girl group, 'Pink Venom' fierce aesthetic, high-fashion luxury outfits, highly charismatic and confident stage presence, pink and black lighting",
    "celeb": "Hollywood A-list celebrity portrait, glamorous red carpet event, hundreds of bright paparazzi camera flashes, wearing extremely expensive luxury designer fashion",
    "taylorswift": "Taylor Swift, The Eras Tour massive stadium concert, wearing a highly sparkly sequined dress, playing an acoustic guitar, surrounded by a massive passionate crowd",
    "pesopluma": "Peso Pluma, Mexican singer, regional Mexican music aesthetic, iconic mullet haircut, wearing highly stylish luxury streetwear, holding a microphone",
    "kingvon": "King Von, Chicago drill hip-hop rapper, O'Block aesthetic, long dreadlocks, wearing urban streetwear and heavy diamond chains, gritty rap video lighting",
    "juicewrld": "Juice WRLD, emo rap legend, 999 aesthetic, holding a microphone, highly emotional performance, moody purple and blue aesthetic lighting",
    "travisscott": "Travis Scott, intense rap concert performance, incredibly raging chaotic crowd, Astroworld aesthetic, massive intense stage pyrotechnics and fire, autotune mic",
    "warrior": "epic ancient warrior, heavily battle-scarred, holding a bloodied sword or axe, standing triumphantly on a war-torn battlefield, cinematic dramatic lighting",
    "knight": "medieval European knight, wearing fully articulated shining plate armor, holding a heavy kite shield and broadsword, heroic stoic stance, ancient stone castle background",
    "samurai": "Japanese samurai warrior, ronin, wearing traditional armor and a straw hat, slowly drawing a razor-sharp katana sword, cherry blossoms falling, dramatic cinematic lighting",
    "cowboy": "Wild West American cowboy, wearing a wide-brimmed Stetson hat and leather chaps, holding a six-shooter revolver, dusty wooden saloon town, high noon standoff tension",
    "king": "majestic royal king, sitting on a massive ornate golden throne, wearing an incredibly heavy jewel-encrusted crown and ermine fur robes, regal and intimidating atmosphere",
    "ninja": "stealthy Japanese ninja shinobi, wearing all-black covert garb covering the face, holding a sharp kunai, jumping silently across temple rooftops under a giant full moon",
    "nature": "breathtaking awe-inspiring nature landscape, National Geographic high-end photography, peaceful and serene pristine environment, 4k extreme detail, perfect natural lighting",
    "mountain": "majestic snow-capped mountain peaks, towering over a deep green valley, crisp alpine air, sharp rocky cliffs, clear blue sky, epic landscape photography",
    "beach": "tropical paradise beach, pristine pure white sand, crystal clear turquoise ocean water, tall green palm trees swaying gently in the wind, sunny relaxing day",
    "flowers": "massive field of blooming highly colorful flowers, vibrant spring season, macro photography, soft warm sunlight, delicate morning dew droplets on petals",
    "sunflower": "bright vivid yellow sunflower field, thousands of large flowers facing the bright sun, clear blue sky background, incredibly happy and warm summer vibe",
    "peony": "beautiful soft pink peony flower, extreme macro photography, lush dense overlapping petals, elegant and soft floral aesthetic, delicate natural beauty",
    "rose": "romantic deep red rose flower, incredibly velvety petals, tiny crystal-clear water droplets resting on the flower, dark moody contrasting background",
    "cherryblossom": "Japanese sakura cherry blossom trees in full bloom, thousands of delicate pink petals falling gently in the spring wind, beautiful ethereal pink aesthetic",
    "lotus": "pure pink lotus flower blooming perfectly in a calm still pond, resting on large green lily pads, highly spiritual, zen and peaceful atmosphere",
    "waterfall": "massive roaring waterfall, thousands of gallons of water crashing violently into a river below, thick misty air, surrounded by lush deep green jungle foliage",
    "ocean": "vast deep blue open ocean, powerful rolling waves, white sea foam crashing, majestic and terrifying seascape, calming but immense water mass",
    "sky": "beautiful dramatic vast sky, massive fluffy white cumulus clouds, breathtaking sunset painting the clouds in pastel pinks, purples, and oranges, majestic atmosphere",
    "disaster": "terrifying natural disaster, cinematic scale destruction, intense raw uncontrollable power of nature, apocalyptic ruined landscape, highly dramatic lighting",
    "storm": "intense terrifying thunderstorm, extremely dark ominous black clouds, massive jagged lightning strike illuminating the sky, heavy torrential rain, dramatic weather",
    "landscape": "epic fantasy-style sweeping landscape, vast sweeping vistas, rolling green hills, glowing god-rays of sunlight breaking through clouds, masterpiece concept art",
    "tree": "giant ancient towering oak tree, massive thick gnarled roots, incredibly lush green leaf canopy, warm sunlight piercing perfectly through the branches",
    "leaf": "extreme macro photography of a single vibrant green leaf, highly detailed intricate veins, a single water droplet acting as a lens reflecting the entire forest",
    "rain": "heavy torrential rain downpour, water splashing violently on a dark asphalt street, moody cinematic lighting, cyberpunk city or dark nature environment",
    "moon": "giant incredibly detailed glowing full moon, dark night sky, highly visible lunar craters and seas, mystical serene and deeply atmospheric nighttime",
    "stone": "ancient mystical glowing runestone, covered in realistic green mossy rock texture, sitting in a dark mysterious magical forest, fantasy element",
    "winter": "beautiful snowy winter landscape, totally frozen solid lake, tall pine trees heavily covered in thick fresh white snow, freezing cold but serene atmosphere",
    "snowman": "cute classic snowman, bright orange carrot nose, wearing a warm red scarf and a black top hat, heavy falling snow, joyful winter wonderland aesthetic",
    "desert": "vast sweeping Sahara desert sand dunes, beautiful golden hour lighting creating sharp shadows, harsh burning sun, totally barren and dry sandy landscape",
    "summer": "perfect bright sunny summer day, totally clear blue skies, highly vibrant green grass, evoking a warm happy carefree nostalgic feeling",
    "forest": "deep enchanted ancient forest, towering thick pine trees, thick mysterious misty fog on the ground, highly atmospheric and magical secluded woods",
    "vehicle": "high-performance luxury vehicle, sleek aerodynamic design, realistic high-end automotive photography, shiny reflective paint, 8k resolution detail",
    "car": "fast sports car driving aggressively on a winding mountain road, intense motion blur on the background and wheels, sleek aerodynamic design, speed",
    "audi": "Audi R8, sleek modern German luxury sports car, highly distinct glowing aggressive LED headlights, parked on a dark rainy city street, sleek silver paint",
    "porsche": "Porsche 911, iconic classic curved silhouette, speeding down a beautiful sunny coastal highway, luxury sports car photography, pure automotive perfection",
    "lamborghini": "Lamborghini Aventador, incredibly aggressive sharp angular design, iconic scissor doors, neon synthwave grid background, the ultimate Italian hypercar",
    "ferrari": "Ferrari, iconic Rosso Corsa red sports car, speeding on a professional racing track, Italian luxury, pure speed and horsepower, automotive masterpiece",
    "mclaren": "McLaren hypercar, distinct dihedral butterfly doors open, incredibly sleek exposed carbon fiber body, highly futuristic and aerodynamic design",
    "bmw": "BMW M4, highly aggressive front kidney grille, drifting violently on a race track, massive amounts of white tire smoke, luxury performance aesthetic",
    "mercedes": "Mercedes-Benz AMG, highly elegant luxury sedan, sleek silver metallic paint, driving smoothly through a modern high-end city at night",
    "toyota": "Toyota Supra Mk4, legendary JDM tuner car, highly modified street racing aesthetic, massive rear wing, speeding through the neon Tokyo underground",
    "ship": "massive towering luxury cruise ship, sailing majestically on the vast open blue ocean, symbols of luxury travel and vacation, highly detailed marine vessel",
    "train": "modern high-speed Japanese bullet train (Shinkansen), zooming incredibly fast past a futuristic neon city, heavy motion blur, pinnacle of modern transportation",
    "boat": "small traditional wooden rowboat, floating completely alone on a perfectly calm misty lake, highly peaceful, serene, and slightly melancholic morning",
    "motorbike": "sleek incredibly fast sports motorcycle, Ducati or Yamaha, racing dangerously fast on a highway, biker wearing full protective leather gear and helmet",
    "formula1racing": "Formula 1 highly advanced open-wheel race car, zooming incredibly fast past the grandstands, titanium skid block sparking brightly on the asphalt, apex motorsport",
    "abstract": "abstract contemporary modern art, totally non-representational, fluid chaotic shapes, highly expressive colors, looking like an expensive modern museum piece",
    "pattern": "perfect seamless geometric pattern, highly intricate repeating mandala, complex tessellation, mesmerizing and satisfying background wallpaper",
    "geometric": "sharp clean geometric shapes, high-quality 3D render, perfectly smooth cubes, spheres, and pyramids, modern minimalist architectural art style",
    "iphonewallpaper": "highly aesthetic mobile phone wallpaper, perfectly framed for 9:16 vertical aspect ratio, extremely clean graphic design, highly satisfying color palette",
    "firework": "massive bursting highly colorful fireworks exploding in the pitch-black night sky, grand celebration, long-exposure photography creating glowing light trails",
    "brokenscreen": "shattered glass screen effect, highly realistic deep spiderweb cracks, broken phone display prank illusion, incredibly sharp and dangerous glass shards",
    "smoke": "thick billowing highly colorful smoke bombs (red, blue, purple), incredibly smooth fluid dynamics, abstract misty background, mysterious and vibrant",
    "love": "deeply romantic love theme, extremely warm and soft aesthetic, depicting deep affectionate emotion, beautiful soft pink and red lighting",
    "heart": "perfectly symmetrical glowing red neon heart shape, ultimate romantic symbol, Valentine's day aesthetic, high-quality 3D rendered glossy icon",
    "couple": "deeply romantic couple, holding hands intimately, walking slowly on the beach at a beautiful sunset, cinematic dark silhouette, conveying deep true love",
    "fnb": "high-end Food and Beverage photography, incredibly appetizing, high-resolution professional food styling, delicious and perfect studio lighting",
    "food": "expensive gourmet restaurant food, beautifully and precisely plated dish, hot steam rising gently, incredibly mouth-watering extreme macro photography",
    "fruit": "fresh incredibly juicy sliced fruits (oranges, strawberries), splashing dynamically in crystal clear water, ultra high-speed photography, freezing the refreshing motion",
    "drink": "ice-cold incredibly refreshing mixed cocktail drink, realistic condensation and water droplets on the glass, fresh fruit garnish, colorful neon bar lighting",
    "religion": "highly respectful religious and spiritual aesthetic, glowing divine heavenly lighting, incredibly sacred and pure atmosphere, Renaissance painting style",
    "god": "ethereal omnipotent divine being, emitting a blindingly beautiful glowing holy light, incredible majestic presence, classic religious Renaissance masterpiece style",
    "cross": "simple traditional wooden Christian cross, brilliant glowing golden sunlight beaming powerfully from behind it, ultimate symbol of faith, hilltop silhouette",
    "flag": "official national flag, waving proudly and majestically in a strong wind, highly photorealistic woven fabric texture, clear perfect blue sky background",
    "vietnam": "beautiful Vietnam cultural aesthetic, women wearing traditional elegant Ao Dai, stunning Ha Long Bay limestone landscape, bustling Hanoi street vibe, cultural pride",
    "brazil": "vibrant Brazil cultural aesthetic, towering Christ the Redeemer statue, incredibly colorful Rio de Janeiro carnival dancers, lush tropical Amazon rainforest",
    "hindugods": "Lord Shiva or Ganesha, incredibly beautiful and intricate Hindu mythology art, emitting a glowing divine aura, highly colorful and culturally rich",
    "mexico": "vibrant Mexico cultural aesthetic, ancient Chichen Itza Mayan pyramid, colorful Dia de los Muertos sugar skulls, highly energetic cultural fiesta",
    "zodiac": "mystical astrological zodiac sign symbol, glowing brightly as a massive constellation in the dark night sky, deeply mystical and magical astrology art",
    "holiday": "highly festive joyful holiday celebration, incredibly warm and happy atmosphere, rich thematic decorations, feeling of family warmth and togetherness",
    "christmas": "incredibly cozy Christmas aesthetic, heavy falling snow outside a window, warm glowing fireplace, beautifully wrapped presents, festive red and green joy",
    "santaclaus": "Santa Claus, plump and jolly, wearing the iconic red suit with white fur, flying a magical sleigh pulled by reindeer across a massive full moon, snowy night",
    "christmastree": "tall beautiful incredibly lush Christmas tree, hundreds of glowing warm fairy lights, highly shiny glass ornaments, a brilliant glowing star on the very top",
    "thanksgiving": "Thanksgiving family dinner table, massive perfectly roasted golden turkey, beautiful autumn leaf decorations, incredibly warm family gathering lighting",
    "newyear": "New Year's Eve massive celebration, gigantic midnight fireworks exploding over a city, glowing neon year sign, incredibly energetic party atmosphere",
    "valentine": "Valentine's Day ultimate romantic aesthetic, dozens of perfect red roses, luxurious heart-shaped chocolate boxes, Cupid's golden arrow, pink and red colors",
    "ramadan": "Ramadan incredibly peaceful aesthetic, glowing golden crescent moon, beautifully intricate traditional glowing lantern (fanoos), peaceful holy night, Islamic art",
    "diwali": "Diwali the festival of lights, dozens of glowing traditional diya oil lamps, incredibly colorful and intricate rangoli floor patterns, joyous Indian celebration",
    "quote": "highly aesthetic typography art, inspiring quote text written in beautiful fonts, perfectly matching aesthetic background, high-quality poster graphic design",
    "sadquote": "melancholic depressing background, raindrops on a dark window, incredibly sad emotional typography quote, dark moody and lonely aesthetic",
    "funnyquote": "highly humorous text quote, extremely bright and colorful background, internet meme style typography, guaranteed to make people laugh, funny joke",
    "lovequote": "deeply romantic love quote typography, very soft pink and white aesthetic, elegant flowing cursive font, perfect for Valentine's day",
    "lifequote": "deep highly philosophical life quote, beautiful nature background like a grand sunset or mountain, highly inspiring and motivational typography",
    "motivatequote": "highly aggressive motivational gym quote, extremely bold impact typography, dark gritty sweaty background, pushing past limits",
    "scenery": "breathtaking awe-inspiring scenery, high-end cinematic landscape photography, ultra wide-angle lens shot, capturing the massive scale of the world",
    "city": "massive modern futuristic metropolis, incredibly towering glass skyscrapers, millions of glowing neon lights, cyberpunk or ultra-clean utopian aesthetic",
    "village": "incredibly cozy European countryside village, ancient cobblestone streets, old rustic stone cottages with thatched roofs, peaceful quiet slow life",
    "architecture": "stunning modern architectural design, imposing brutalist concrete structures or impossibly sleek glass designs, professional architectural photography",
    "home": "incredibly cozy aesthetic bedroom interior, very warm string lighting, soft comfortable messy bed, perfect lofi study space, relaxing personal sanctuary",
    "wonders": "one of the Seven Wonders of the World (e.g., Pyramids, Taj Mahal), incredibly majestic historical monument, awe-inspiring ancient massive architecture",
    "road": "incredibly long completely empty asphalt highway road, stretching infinitely straight to the horizon, vast desert landscape, ultimate road trip freedom feeling",
    "season": "beautiful distinct seasonal transition, showing changing weather and foliage, highly expressive environmental mood and atmospheric lighting",
    "spring": "Spring season at its peak, thousands of blooming highly colorful flowers, fresh incredibly green grass, bright warm joyful sunlight, feeling of rebirth",
    "autumn": "Autumn fall season, thousands of orange, red, and yellow maple leaves falling gently, cozy sweater weather vibe, perfect warm golden hour lighting",
    "meme": "classic internet meme aesthetic, incredibly funny relatable reaction image, highly recognizable viral humor format, bold impact font, internet culture",
    "middlefinger": "human hand clearly showing the middle finger gesture, highly aggressive rebellious punk attitude, blurred background to focus on the hand",
    "67": "the number 67 prominently displayed, extremely bold typography, glowing neon numbers against a dark textured background, highly creative graphic design",
    "warning": "highly visible danger warning alert, extremely bold red and yellow caution colors, universal hazard symbol, gritty industrial danger zone aesthetic",
    "warningsign": "triangular bright yellow warning sign, massive bold black exclamation mark, standing in a highly dangerous industrial or construction zone",
    "warningtext": "WARNING text written in an extremely bold red hazard font, terrifying digital glitching screen effect, critical computer error message aesthetic",
    "manhua": "beautiful Chinese Manhua art style, ancient xianxia cultivation setting, characters wearing incredibly elegant flowing hanfu robes, breathtaking historical aesthetic",
    "tianguancifu": "Heaven Official's Blessing (TGCF), Xie Lian and Hua Cheng, incredibly beautiful romantic manhua art, iconic red umbrella, glowing silver butterflies, deep love",
    "donghua": "extremely high quality 3D Chinese Donghua animation, epic wuxia fantasy, cultivators riding flying swords, incredibly flashy magical martial arts combat",
    "xianni": "Renegade Immortal (Xian Ni), Wang Lin character, incredibly cold ruthless ancient cultivator, epic xianxia magical combat, bloody and brutal slaughter",
    "manga": "highly detailed traditional Japanese manga panel, black and white ink drawing style, precise screentones, extremely dramatic shading and speed lines",
    "vagabond": "Vagabond manga style, Takehiko Inoue legendary art, Miyamoto Musashi, highly realistic and gritty samurai ink drawing, incredibly intense brush strokes",
    "other": "miscellaneous highly creative concept, extremely detailed central focal point, standing out uniquely against a complementary background",
    "ghost": "spooky translucent floating ghost, haunting an incredibly creepy abandoned house, emitting a glowing blue ectoplasm aura, classic Halloween horror aesthetic",
    "sillyface": "incredibly funny silly facial expression, highly exaggerated cartoonish human features, huge goofy smile, crossed eyes, pure comedy",
    "glitter": "incredibly sparkling shiny glitter texture, extreme macro photography, reflecting a massive rainbow of light, highly glamorous and luxurious aesthetic",
    "logo": "highly professional minimalist corporate logo design, perfectly sleek vector graphic, premium brand identity, presented on a clean 3D mockup",
    "emoji": "high-quality 3D rendered emoji face, incredibly detailed glossy plastic texture, highly expressive specific emotion, modern digital communication",
    "bt21": "BT21 Line Friends characters, incredibly cute colorful mascots (Tata, Chimmy, Cooky), highly vibrant Kpop BTS aesthetic, adorable cartoon style",
    "fire": "massive roaring incredibly hot fire flames, intense glowing yellow and orange heat, pitch-dark background, highly realistic physics of combustion",
    "labubu": "Labubu designer art toy figure, highly iconic cute but creepy monster design, massive jagged teeth smile, trendy expensive collectible toy aesthetic",
    "flashlight": "incredibly bright piercing beam of light from a heavy-duty flashlight, cutting sharply through thick dark fog, highly mysterious exploration aesthetic",
    "money": "massive stacks of crisp hundred dollar bills, money flying through the air, highly wealthy and luxurious aesthetic, shiny gold coins scattered",
    "dollars": "US dollar bills, extreme macro shot focusing perfectly on Benjamin Franklin's face, highly detailed green paper money texture, symbol of financial wealth",
    "yinyang": "classic Yin and Yang symbol, perfectly balanced black and white halves, emitting a mystical glowing aura, deep Daoist philosophy and balance",
    "doublewallpaper": "matching couple wallpaper designed in two distinct halves, highly cohesive aesthetic perfectly connecting across two separate mobile phone screens",
    "crybaby": "Pop Mart Crybaby designer figure, iconic massive tears streaming down the face, incredibly cute but deeply sad toy aesthetic, high-end collectible",
    "twinkletwinkle": "twinkle twinkle little star concept, incredibly magical glowing starlight, gentle nursery rhyme aesthetic, dreamy and highly peaceful dark night sky"
}

# ==========================================
# 2. TẠO LIST ĐỘNG TRỰC TIẾP TỪ DICTIONARY 
#    (Chống lệch Index)
# ==========================================

STYLES = list(STYLE_PROMPT_MAP.keys())
COLORS = list(COLOR_PROMPT_MAP.keys())
TAGS_OBJECT = ["None"] + list(SUBJECT_PROMPT_MAP.keys())

TAGS_MOOD = ["Happy", "Sad", "Lonely", "Chill", "Funny", "None"]
TAGS_GENDER = ["Boy", "Girl", "Man", "Woman", "Couple", "None"]

